const{chromium}=require('playwright'),assert=require('node:assert/strict');
const{ShopHarness,BASE}=require('./shop_ops_harness.cjs');
(async()=>{const h=new ShopHarness();let b,c;const errors=[];try{
 await h.setup();b=await chromium.launch({headless:true});c=await b.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});await h.attach(c,'owner');const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
 await p.goto(BASE+'/admin/',{waitUntil:'domcontentloaded'});await p.waitForSelector('.sh-quick');
 await p.locator('[data-act=import]').click();await p.locator('[data-opening]').first().waitFor();
 let boot=await h.call('owner','bootstrap');assert.equal(boot.products.length,10);assert.ok(boot.products.every(x=>x.opening_required&&x.stock===0));
 const prod=boot.products.find(x=>x.id===1);
 await p.locator('[data-opening="1"]').click();await p.locator('[data-act=positive-opening]').click();let form=p.locator('.sh-modal form').last();await form.locator('[data-rowfield=qty]').fill('5');await form.locator('[data-rowfield=price]').fill('100');await form.locator('button[value=post]').click();await p.locator('[data-act=print-doc]').waitFor();assert.equal((await h.call('owner','bootstrap')).products.find(x=>x.id===1).stock,5);await p.locator('.sh-close').last().click();
 await p.locator('[data-opening="2"]').click();await p.locator('[data-act=zero-opening]').click();await p.locator('.sh-modal').waitFor({state:'hidden'});assert.equal((await h.call('owner','bootstrap')).products.find(x=>x.id===2).opening_required,false);
 await p.locator('[data-nav=team]').click();await p.locator('[data-act=new-staff]').click();form=p.locator('.sh-modal form').last();await form.locator('[name=name]').fill('کارمند خرید جدید');await form.locator('[name=email]').fill('new-buyer@example.invalid');await form.locator('[name=department]').selectOption('purchasing');await form.locator('[type=submit]').click();await p.getByRole('heading',{name:'اطلاعات ورود خصوصی کارمند',exact:true}).waitFor();assert.match(await p.locator('.sh-credentials').innerText(),/new-buyer@example.invalid/);await p.locator('.sh-close').last().click();assert.ok((await h.call('owner','staff')).some(x=>x.email==='new-buyer@example.invalid'&&x.permissions['purchases.create']===true&&x.permissions['purchases.edit']!==true));
 // Barcode/code entry adds a line rapidly without a second catalogue/form.
 await p.keyboard.press('F2');await p.locator('[data-scan]').waitFor();await p.locator('[data-scan]').fill(prod.sku);await p.locator('[data-scan]').press('Enter');form=p.locator('.sh-modal form').last();assert.equal(await form.locator('[data-rowfield=product_id]').inputValue(),'1');await form.locator('[name=paid]').fill(String(prod.sale_price));await form.locator('button[value=post]').click();await p.locator('[data-act=print-doc]').waitFor();
 const sale=(await h.call('owner','documents',{section:'sales'}))[0];assert.equal(sale.lines[0].qty,1);assert.equal(sale.paid,sale.total);
 const pop=c.waitForEvent('page');await p.locator('[data-act=print-doc]').click();const print=await pop;await print.waitForLoadState('domcontentloaded');assert.match(await print.locator('body').innerText(),/فاکتور فروش/);assert.equal(await print.getByText('بهای تمام‌شده',{exact:false}).count(),0);assert.equal(await print.locator('tbody tr').count(),1);await print.close();
 await p.locator('[data-act=return-doc]').click();form=p.locator('.sh-modal form').last();await form.locator('button[value=post]').click();await p.locator('[data-act=print-doc]').waitFor();assert.equal((await h.call('owner','bootstrap')).products.find(x=>x.id===1).stock,5);await p.locator('.sh-close').last().click();
 await p.locator('[data-nav=finance]').click();await p.locator('[data-act=new-receipt]').click();form=p.locator('.sh-modal form').last();await form.locator('[name=kind]').selectOption('capital');await form.locator('[name=amount]').fill('1000');await form.locator('[name=account]').selectOption('1010');await form.locator('[type=submit]').click();await p.locator('.sh-modal').waitFor({state:'hidden'});
 await p.locator('[data-act=new-receipt]').click();form=p.locator('.sh-modal form').last();await form.locator('[name=kind]').selectOption('transfer');await form.locator('[name=amount]').fill('100');await form.locator('[name=account]').selectOption('1010');await form.locator('[type=submit]').click();await p.locator('.sh-modal').waitFor({state:'hidden'});const finance=await h.call('owner','payments');assert.ok(finance.some(x=>x.kind==='transfer'&&x.amount===100));
 assert.deepEqual(errors,[]);console.log('PASS advanced shop UI: conservative catalogue onboarding, valued opening/zero confirmation, employee creation with least privilege, quick SKU entry, receipt/PDF view without private cost, return, capital and transfer. Isolated SQL only.');
}finally{if(c)await c.close();if(b)await b.close();await h.cleanup();}})().catch(e=>{console.error(e);process.exitCode=1});
