/* Server endpoint contract: auth, physical table isolation, public-only fields, atomic CAS. */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path'),{transformSync}=require('esbuild');
const src=fs.readFileSync(path.resolve(__dirname,'../../supabase/functions/web-sync/index.ts'),'utf8').replace(/import \{ createClient \} from [^;]+;/,'');
const code=transformSync(src,{loader:'ts',format:'iife',target:'es2020'}).code;
function boot(){
 const rows=new Map(),tables=[];let handler;
 const db={auth:{getUser:async token=>token==='admin'?{data:{user:{id:'web-admin',app_metadata:{web_admin:true}}}}:token==='member'?{data:{user:{id:'member',app_metadata:{},user_metadata:{web_admin:true}}}}:{data:{user:null},error:{code:'bad_token'}}},from(name){
  tables.push(name);assert.equal(name,'web_store','Endpoint may only access independent website table');
  return {insert(v){return {select:async()=>{if(rows.has(v.k))return{error:{code:'23505'}};rows.set(v.k,structuredClone(v));return{data:[{k:v.k,updated_at:v.updated_at}]};}};},update(v){const filters={};const q={eq(k,x){filters[k]=x;return q;},select:async()=>{const old=rows.get(filters.k);if(!old||old.updated_at!==filters.updated_at)return{data:[]};rows.set(old.k,{...old,...structuredClone(v)});return{data:[{k:old.k,updated_at:v.updated_at}]};}};return q;}};
 }};
 vm.runInNewContext(code,{Deno:{env:{get:()=>''},serve:f=>handler=f},createClient:()=>db,Response,Request,TextEncoder,Date,console});
 const post=async(body,token='admin',method='POST')=>{const r=await handler(new Request('https://mock/web-sync',{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(method==='POST'?{body:typeof body==='string'?body:JSON.stringify(body)}:{})}));return {status:r.status,data:await r.json()};};
 return {rows,tables,post};
}
let passed=0;async function test(n,fn){await fn();passed++;console.log('PASS '+n)}
(async()=>{
 await test('Anonymous and invalid bearer requests cannot publish',async()=>{const x=boot();for(const token of ['', 'not-a-session'])assert.equal((await x.post({action:'kv',rows:[]},token)).status,401);assert.equal(x.tables.length,0);});
 await test('Only server-owned web_admin metadata grants publication; user_metadata cannot grant itself the role',async()=>{const x=boot();assert.equal((await x.post({action:'kv',rows:[]},'member')).status,403);assert.equal(x.tables.length,0);});
 await test('Academy/protected/unknown keys are rejected without accessing any table',async()=>{const x=boot();for(const k of ['ga_academy','ga_players','ga_users','web_users','web_setting_constructor'])assert.equal((await x.post({action:'kv',rows:[{k,v:{},base:null}]})).status,400);assert.equal(x.tables.length,0);});
 await test('Valid public setting writes only web_store and returns authoritative timestamp',async()=>{const x=boot();const r=await x.post({action:'kv',rows:[{k:'web_setting_hero',v:{line1:'Synthetic'},base:null,updated_at:'2099-01-01T00:00:00Z'}]});assert.equal(r.status,200);assert.equal(r.data.put,1);assert.equal(r.data.rows[0].k,'web_setting_hero');assert.notEqual(r.data.rows[0].updated_at,'2099-01-01T00:00:00Z');assert.deepEqual(x.tables,['web_store']);});
 await test('Fresh insert cannot overwrite an already-created record',async()=>{const x=boot(),body={action:'kv',rows:[{k:'web_setting_hero',v:{line1:'A'},base:null}]};assert.equal((await x.post(body)).status,200);body.rows[0].v.line1='B';assert.equal((await x.post(body)).status,409);assert.equal(x.rows.get('web_setting_hero').v.line1,'A');});
 await test('Update is atomic compare-and-set; stale revision never overwrites',async()=>{const x=boot(),body={action:'kv',rows:[{k:'web_setting_hero',v:{line1:'A'},base:null}]};const first=await x.post(body);const base=first.data.rows[0].updated_at;const stale=await x.post({action:'kv',rows:[{k:'web_setting_hero',v:{line1:'B'},base:'2000-01-01T00:00:00Z'}]});assert.equal(stale.status,409);assert.equal(x.rows.get('web_setting_hero').v.line1,'A');assert.equal((await x.post({action:'kv',rows:[{k:'web_setting_hero',v:{line1:'C'},base}]})).status,200);assert.equal(x.rows.get('web_setting_hero').v.line1,'C');});
 await test('Unapproved or private feedback fields cannot be stored publicly',async()=>{const x=boot();for(const v of [{id:1,name:'Test',status:'pending'},{id:1,name:'Test',status:'approved',phone:'private'},{id:1,name:'Test',email:'private'},{id:1,name:'Test',password:'private'}])assert.equal((await x.post({action:'kv',rows:[{k:'web_testimonial_1',v,base:null}]})).status,400);assert.equal(x.tables.length,0);});
 await test('Gate accepts only a digest, not a plaintext unlock code',async()=>{const x=boot();assert.equal((await x.post({action:'kv',rows:[{k:'web_setting_shop_gate',v:{enabled:true,code:'secret'},base:null}]})).status,400);assert.equal((await x.post({action:'kv',rows:[{k:'web_setting_shop_gate',v:{enabled:true,codeHash:'a'.repeat(64),codeLength:8},base:null}]})).status,200);});
 await test('Tombstone is a public soft deletion, not an academy delete operation',async()=>{const x=boot();assert.equal((await x.post({action:'kv',rows:[{k:'web_product_23',v:{id:23,_deleted:true},base:null}]})).status,200);assert.equal(x.rows.get('web_product_23').v._deleted,true);assert.equal((await x.post({action:'kv',rows:[{k:'web_product_24',v:{id:23,_deleted:true},base:null}]})).status,400);});
 await test('Only one explicit revision-bearing record is acknowledged per request',async()=>{const x=boot();assert.equal((await x.post({action:'kv',rows:[]})).status,400);assert.equal((await x.post({action:'kv',rows:[{k:'web_setting_hero',v:{line1:'A'}}]})).status,400);assert.equal(x.tables.length,0);});
 await test('UTF-8 body limit rejects a large payload without partial write',async()=>{const x=boot();const r=await x.post({action:'kv',rows:[{k:'web_setting_hero',v:{line1:'گ'.repeat(1100000)},base:null}]});assert.equal(r.status,413);assert.equal(r.data.maxBytes,2*1024*1024);assert.equal(x.tables.length,0);});
 console.log(`PASS — ${passed} isolated web-sync server scenarios; zero live data.`);
})().catch(e=>{console.error(e);process.exitCode=1});
